plantuml_markdown:
  server: http://localhost:4444  # PlantUML server, for remote rendering
  # other global options
  #cachedir: /tmp                            # set a non-empty value to enable caching
  format: png                               # default diagram image format
  #classes: class1,class2                    # default diagram classes
  #title: UML diagram                        # default title (tooltip) for diagram images
  #alt: UML diagram image                    # default `alt` attribute for diagram images
  #priority: 30                              # plugin priority; the higher, the sooner will be applied (default 30)
